version: "3.9"
services:
  frontend:
    build: ./
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    environment:
      - VITE_API_BASE=http://backend:8000
  backend:
    build: ./MCP_Skeleton/server
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./MCP_Skeleton/server:/app
